
export const API_ENDPOINTS = {
  LOGIN: '/login',
  REGISTER: '/register',
  LOGOUT: '/logout',
  FORGET_PASSWORD: '/forget-password',
  CATEGORIES: '/katergorier',
  CATEGORIES_2: '/categories.json',
  CATEGORIES_ANCIENT: '/categories_ancient.json',
  FEATURED_CATEGORIES: '/featured_categories.json',
  COLLECTIONS: '/collections.json',
  BRANDS: '/brands',
  PRODUCTS: '/products',
  PRODUCTS_2: '/products_2.json',
  PRODUCTS_ANCIENT: '/products_ancient.json',
  FEATURED_PRODUCTS: '/featured',
/*   FEATURED_PRODUCTS_ANCIENT: '/featured_products_ancient.json',
 */  TOP_SELLER_PRODUCTS: '/products_top_seller.json',
  ON_SELLING_PRODUCTS: '/saleProdukter',
  PRODUCT: '/produkt/',
  RELATED_PRODUCTS: '/related',
  BEST_SELLER_PRODUCTS: '/products_best_seller.json',
  NEW_ARRIVAL_PRODUCTS: '/nyaProdukter',
  POPULAR_PRODUCTS: '/products_popular.json',
  NEW_ARRIVAL_PRODUCTS_ANCIENT: '/products_new_arrival.json',
  FLASH_SALE_PRODUCTS: '/flashSale',
/*   FLASH_SALE_PRODUCTS_ANCIENT: '/products_flash_sale_ancient.json',
 */  SHOPS: '/shops.json',
  SHOP: '/shop.json',
  SEARCH: '/search',
  ORDERS: '/orders.json',
  ORDER: '/order.json',
  NEWSLETTER: '/nyhetsbrev',
  SUPPORT_FORM: '/support-form',
  CONTACT_FORM: '/contact-form'
};
